language: node_js
sudo: required
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
env:
  global:
  - secure: fBXZ/GY88LF62pZFNTmL+ZuO7fF3IK/jqFg9ffNIVEydFCGxZKnJZ59FCvfQxPKBGBkqaInPTkRwda2LUr4JK6ZvnA0HlYNwKWNbVNVyWUdZNptiU5TFwAaaEv/89LFMNq7DigElr15CEof0ni6Su5fcz9YNS0+B8GiQKw/39GY=
  - secure: VOlf623uUKEmua/zdqMO5Q8ZeQhbRJE6ZyPKdNsp2DYrvevrSfK7Y4WAqsmn/YY8Q41gkOaNjMa13pMORe7cXtOPB7k6FajUHBRBBSaJC4l7sZo/YirjwMDwhb+p48js4pr9cv/1BLwwMmTp4xK81ODdT0QPSzO/lLsXUPLJKes=
node_js: stable
addons:
  firefox: '46.0'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
dist: trusty
